version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana-dashboard:/var/lib/grafana/dashboards
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  db:
    container_name: postgres_indexer
    image: postgres:alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: indexer
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
